---
title: Assignment 3 Energy project economics
format: 
  html: 
    theme: cosmo
    css: /styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
  pdf: 
    documentclass: article
    #classoption: [landscape]
    lof: false
    lot: false
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded
    #fontfamily: xelatex
    colorlinks: true
#draft: true
---

## 1. A tale of two nuclear plants

### Background  

Please read the story of the [Shoreham Nuclear Power Plant](https://en.wikipedia.org/wiki/Shoreham_Nuclear_Power_Plant) and the [Diablo Canyon Power Plant](https://en.wikipedia.org/wiki/Diablo_Canyon_Power_Plant). One plant never commerically operated and was decommisioned and the rate-payers are still paying the construction costs, while the other is offered to extend operation in the midist of California's clean energy quest.


### Questions

1. How long does it take for Long Island residents to pay off the construction and decommission of Shoreham Nuclear Power Plant? (Bad energy investment decisions have drastic consequences)  (**1.5pt**)

Key assumptions: LILCO attaches a **3 percent** surcharge to LI electric bills for 30 years to pay off the nuclear facility’s approximately **$6 billion** price tag in 1989.   
Residential rates in 2020: **21.22 cents/kWh**   
Long Island total electricity consumption in 2020: **20 TWh**   
Discount rate: **4%**   
Assuming the real value of total annual surcharge stays the same. You can use 2020 as a base year, and convert the 6 billion price tag to 2020 value, and then divided by the 2020 total surcharges.   

2. Diablo Canyon generated nearly 9 percent of Cailifornia's electricity in 2021 and roughly 15 percent of the State's clean energy production. Diablo Canyon Power Plant is granted a 5 year extention beyond its scheduled shutter at 2025. What's the LCOE of Diablo Canyon Power Plant in its extended operation period (2026-2030)?  (**1.5pt**)
 
Nameplate capacity: **2,256 MW**   
Capacity factor: **80%**   
Discount rate: **4%**   
Key assumptions: **1.4** billion forgivable loans which can be seen as the investment, past investments are sunk costs that no need to be considered in this calculation. 


## 2. EV or ICE, is it still a question?

EV sales globally are seeing exponential growth. Let's do some project ecoconomics calculation to see if it make sense to purchase an EV, vs, an internal combustion engine (ICE) vehicle.  (**3pt**)

A basic Chevrollet Bolt EV starting at **$29,700**, and an Honda Civic ICE starting at **$23,950**, according to official releases.

Assume you drive **13,476** miles per year as average U.S. drivers do^[Federal Highway Administration, 2022, https://www.fhwa.dot.gov/ohim/onh00/bar8.htm].
Electricity price: **\$0.2/kWh**; Gasoline price: **\$3.5/gallon**.
Efficiency: EV: **28kWh/100mile**; ICE: **30mile/gallon** (mpg)
Life-time: **10years**
Resale value after 10 years: EV: **\$5,000**; ICE: **\$10,000**
Discont rate: **4%**

1. Calculating the NPV of the EV and ICE, and decide which vehicle should you purchase based on economics?  
2. IRA offers **\$7,500** tax credit^[https://www.irs.gov/credits-deductions/credits-for-new-clean-vehicles-purchased-in-2023-or-after] for EV purchase, will that change your decision?  
3. What if the discount rate is **8%**, will that change your decision?  
4. Calculating the carbon mitigation by driving an EV at New York State during the 10 years?  New York State grid carbon intensity is on average **0.55 short tons CO2 per MWh**^[https://www.nyserda.ny.gov/-/media/Project/Nyserda/Files/Publications/Energy-Analysis/22-18-Projected-Emission-Factors-for-New-York-Grid-Electricity.pdf] of electricity generated. And the carbon intesity of finished gasoline is **8.10kgCO2/gallon**^[https://www.eia.gov/environment/emissions/co2_vol_mass.php].
5. What's the cost of conserved CO2 in this case? (Hint: NPV difference/total carbon mitigation)  


## Further readings

Get to understand what composites the 6 billion price tag, and what are the hidden costs? Check the political economy of the energy policy and investment decisions.

New York Times, June 19, 1983. [How Long Island Will Pay For Shoreham](https://www.nytimes.com/1983/06/19/nyregion/how-li-will-pay-for-shoreham.html)  

Timothy Bolger and Christopher Twarowski, June 11, 2009, [Nuclear Waste: 20 Years After Shoreham’s Closure](http://archive.longislandpress.com/2009/06/11/nuclear-waste-20-years-after-the-closure-of-the-shoreham-power-facility/)

Nathan Rott, September 1, 2022. [California lawmakers extend the life of the state's last nuclear power plant](https://www.npr.org/2022/09/01/1119778975/california-lawmakers-extend-the-life-of-the-states-last-nuclear-power-plant)  





