---
title: Assignment 2 Energy data analysis and policy
format: 
  html: 
    theme: cosmo
    css: /styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
  pdf: 
    documentclass: article
    #classoption: [landscape]
    lof: false
    lot: false
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded
    #fontfamily: xelatex
    colorlinks: true
#draft: true
---

## 1. What if Americans turn to small cars and electric vehicles?

In your first policy response, you discussed the impact and policy responses to America's big car problem. This assignment gives you the opportunity to practice with data and policy analysis. You will navigate through common energy and carbon data, make reasonable assumptions, and calculate policy-relevant metrics. 

First, let's make some assumptions on the market penetration of small cars and electric vehicles: 

Key assumptions (all based on 2022 data):

- Average annual miles per vehicle: 11,000 miles^[https://afdc.energy.gov/data/10309]\
- Averge fuel efficiency^[https://thundersaidenergy.com/downloads/us-vehicle-sales-by-fuel-economy-cars-trucks-and-suvs]: \
  - Subcompact/small cars: 33 mile per gallon (mpg)\
  - Big cars/pickup trucks: 20 mpg\
- Total registerd personal and commercial vehicles: 278,870,463^[https://www.forbes.com/advisor/car-insurance/car-ownership-statistics]\
- Big cars (large, crossover, SUVs) market share: 65%^[https://www.autoinsurance.com/research/car-ownership-statistics/]\

### Questions

1. **Oil savings with a switch to smaller cars**: If the U.S. replaces half of its big cars (large, crossover, SUVs) with small cars (subcompact, compact, and midsize cars) in 2022, how much gasoline can the US save in one year? Compare your result with U.S. daily oil imports. (1pt)

2. **EV transition by 2050**: Assume the U.S. replaces all vehicles with EVs by 2050. How much gasoline could be avoided annually in 2050, compared to 2022? Additionally, how much more electricity would be required to charge all vehicles in a year? Assumming the total number of vehicles remains the same and the average combined efficiency of 25 kWh/100 miles^[https://en.wikipedia.org/wiki/Electric_car_EPA_fuel_economy]. (1.5pts)



## 2. UK coal phase out and lessons for other countries

### Background  

In in policy response last week, you explored how the UK is set to close its last coal power plant by 2024. Read more on coal phase out [here](https://www.wri.org/insights/countries-phasing-out-coal-power-fastest). You can download historical coal consumption data for any country from [Our Wold in Data](https://ourworldindata.org/grapher/coal-consumption-by-country-terawatt-hours-twh?tab=table). Please note that the unit is in TWh ranther than traditional tons.


### Questions

1. **Delayed UK coal phase-out**: If the UK delayed its coal phase out by six years, how much additional coal would consume, and how much more carbon emissions would this result in? Assume starting 2023 (UK Energy Act), a linear declince to zero coal consuption by 2030, instead of 2024. Use an emission factor of 91.2tCO2/TJ, and 1TWh = 3600 TJ (1.5pts) 

2. **Coal phase-out in other countries**: Choose a country of interest (e.g. the U.S., China, Chile) and apply a similar analysis to show the benefits of an earlier coal phase out. For example, what if China phases out coal by 2040 instead of 2050. (1pt)
