---
title: Fall 2024 Course Schedule
page-layout: full
repo-actions: false
---

<!--This is my personal clarity, please delete or replace with your own clarity-->
{{< include /files/includes/_msclarity.qmd >}}

- [Readings](readings.qmd)
- [Students](students.qmd)

| Week | Date  | Lecture       | Guest Speaker        | Assignment     |
| ---- | ----- | ------------------------------------------- | ------------------------------------------ | -------------- |
| 1    | 9/2   | Labor Day - No session         |             |           |
| 2    | 9/9   | [Introduction: Grand challenges](lecture1.qmd)   |        | HW1 |
| 3    | 9/16  | [Make sense of energy and climate numbers](lecture2.qmd)    | [Ketch Morse](https://drganghe.github.io/climate-guest-speakers/speakers/richard-morse/) |   |
| 4    | 9/23  | [Climate impact assessments](lecture3.qmd)    | [Dr. Shirley Gallagher](https://drganghe.github.io/climate-guest-speakers/speakers/shirley-gallagher/) |   |
| 5    | 9/30  | [Energy systems overview](lecture4.qmd)  | [Dr. Kaifang Luo](https://drganghe.github.io/climate-guest-speakers/speakers/kaifang-luo/) |    | 
| 6    | 10/7  | [Energy project economics](lecture5.qmd)  | [Simi George](https://drganghe.github.io/climate-guest-speakers/speakers/simi-george/) | HW2 |
| 7    | 10/15 | [Energy demand, energy and economy](lecture6.qmd)  | [Maryam Mozafari](https://drganghe.github.io/climate-guest-speakers/speakers/maryam-mozafari/)   |      |
| 8    | 10/21 | [Energy sources and conversion technologies](lecture7.qmd)  | [Fabio Passaro](https://drganghe.github.io/climate-guest-speakers/speakers/fabio-passaro/)  | HW3 |
| 9    | 10/28 | [Energy efficiency, behavior, and sustainable consumption](lecture8.qmd)  | [Dr. Liqun Peng](https://drganghe.github.io/climate-guest-speakers/speakers/liqun-peng/)  |    |
| 10   | 11/4  | [Energy access, justice, and transition](lecture9.qmd) | [Samuel Vaillancourt](https://drganghe.github.io/climate-guest-speakers/speakers/samuel-vaillancourt/)   |       |
| 11   | 11/11 | [Energy, environment, climate, and human health](lecture10.qmd)  | [Bharathi Esakkimuthu](https://drganghe.github.io/climate-guest-speakers/speakers/bharathi-esakkimuthu/) | Proposal       |
| 12   | 11/18 | [Climate policy responses](lecture11.qmd)    | [Mohsen Fatemi](https://drganghe.github.io/climate-guest-speakers/speakers/mohsen-fatemi/) | HW4 |
| 13   | 11/25 | [Big data and AI for climate change and power sector decarbonization](lecture12.qmd) |     | Thanksgiving   |
| 14   | 12/2  | [Uncertainties in policy analysis and review and summary](lecture13.qmd)  |       |        |
| 15   | 12/9  | Presentations     |      |      |
| 16   | 12/16 | [Student Projects](students.qmd) |       | Policy memo    |
