---
title: Policy Memo
format: 
  html: 
    theme: cosmo
 #   css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true
  pdf: 
    documentclass: article
    #classoption: [landscape]
    lof: false
    lot: false
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded
    #fontfamily: xelatex
    colorlinks: true
---

<!--This is my personal clarity, please delete or replace with your own clarity-->
{{< include /files/includes/_msclarity.qmd >}}

## Introduction

Your final project is a demonstration of your master of the concepts and skills discussed in the class. You can choose an energy related topic of your own interest. In each lecture, I listed sample analytic questions of the chapter and I hope that offers you some inspiration. I also post below sample topics.

### Sample policy memo topics

- What would be an opitimal congestion price in NYC?
- Policies to enhance supply chains of offshore wind in NYS?
- What NYSERDA should do to promote heat pump installations?
- How to help disadvantaged communities to adapt climate change?


## Proposal

Please submit an one-page proposal letting me know your topic, briefly explain why the topic, what data and analytic methods you plan to use, and any potential challenges and how would you address them.


## Presentation

Your presentation should about 15-20mins long summarizing your work. Please submit both the video and slides.

Your presentation will be graded by the following criteria:

1. Nice presence [4pt]
2. Clear presentation of project ideas and insights [4pt]
3. Mastery of the subject [4pt]
4. Presentation design and style [4pt]
5. Overall impression [4pt]


## Policy Memo

A typical policy includes an introduction (topic or problem), scope of problem, current approach, **proposed approach/policies and evidences**, conclusion. Your policy memo should be double spaced, 2-3 pages long, excluding appropriately cited references. 

Your policy will be graded by the following criteria:

1. Creativity in defifing a topic/problem [5pt]
2. Rigorous analysis [5pt]
3. Clear writing, presentation, visulization [5pt]
4. Overall impression [5pt]

## Student Projects

- [Fall 2024](2024/students.qmd)
- [Fall 2023](2023/students.qmd)


## References

[How to Write a Policy Memo That Matters](https://harris.uchicago.edu/files/how_to_write_a_policy_memo_that_matters_0.pdf)

[Stanford Law Policy Memo Guidelines](https://law.stanford.edu/wp-content/uploads/2015/04/Policy-Memo-Guidelines-2.pdf)

[Lauren Brodsky, How to write policy memos](https://www.hks.harvard.edu/sites/default/files/Academic%20Dean's%20Office/communications_program/workshop-materials/Slides_How%20to%20Write%20a%20Policy%20Memo%202_14_22.pdf)

[Policy Memo Database](https://policymemos.hks.harvard.edu/policy-memo-databases)