---
title: Resources
---

<!--This is my personal clarity, please delete or replace with your own clarity-->
{{< include /files/includes/_msclarity.qmd >}}

## NYC/NYS resources

[NYSERDA](https://www.nyserda.ny.gov/Impact-Greenhouse-Gas-Emissions-Reduction)

[New York State Climate Impacts Assessment](https://nysclimateimpacts.org/)

[New York City Panel on Climate Change (NPCC)](https://climateassessment.nyc/), [The 4th Assessment](https://climateassessment.nyc/assessments/)

[Climate Week NYC](https://www.climateweeknyc.org/)

[Mayor's Office of Climate & Environmental Justice](https://climate.cityofnewyork.us/)


## Baruch/CUNY climate resources

CUNY Climate Action Collaborative ([CCAC](https://blogs.baruch.cuny.edu/climateaction/))

CUNY [Climate Scholars](https://blogs.baruch.cuny.edu/climateaction/)

CUNY [Climate Change Consortium (C3)](https://www.cuny.edu/research/research-development-programs/cuny-climate-consortium/)

Baruch [Conference on Climate Research, Teaching, and Collaboration](https://baruch.cuny.edu/climateconference/)


## Climate jobs

IISD [Climate Change Jobs](https://jobs.iisd.net/)

[Climate Jobs New York](https://www.climatejobsny.org/)


## Energy and climate news

New York Times [Climate Forward](https://www.nytimes.com/column/climate-fwd)

The Economist [Climate Issue](https://www.economist.com/climate-change)

E&E [News](https://www.eenews.net/)

[Carbon Brief](https://www.carbonbrief.org/)

[Climate Central](https://www.climatecentral.org/)

EIA [Today in Energy](https://www.eia.gov/todayinenergy/)

[Our World in Data](https://ourworldindata.org/)


## Energy, climate, and carbon data and analysis

EIA, [Energy Conversion and Calculator](https://www.eia.gov/energyexplained/units-and-calculators/energy-conversion-calculators.php)

IEA, [World Energy Outlook](http://www.worldenergyoutlook.org) series

EIA, [International Energy Outlook](http://www.eia.gov) series. 

[Global Energy Monitor](https://globalenergymonitor.org)

IEA, [CO₂ Emissions from Fuel Combustion](http://www.iea.org)

[Carbon Dioxide Information Analysis Center](http://cdiac.ornl.gov), Oak Ridge National Laboratory, US Department of Energy

[Greenhouse Gas Protocol](http://www.ghgprotocol.org), World Resources Institute

[Energy and Carbon Emission Harmonized Database](http://webarchive.iiasa.ac.at), IIASA

[Carbon Monitor](https://www.carbonmonitor.org)


## Modelling community

[Integrated Assessment Modeling Consortium](https://www.iamconsortium.org/)

[Macro-Energy Systems](https://www.macroenergysystems.org/)

National Center for Atmospheric Research, [Community Earth System Model](https://www.cesm.ucar.edu/)

Stanford University, [Energy Modeling Forum](https://emf.stanford.edu/)

Stockholm Environment Institute, [Community of Energy, Environment, and Development](https://leap.sei.org/)

[Open Energy Modeling Initiative](https://forum.openmod.org/)

- [List of models](https://wiki.openmod-initiative.org/wiki/Open_Models)
- [Data](https://wiki.openmod-initiative.org/wiki/Data)

[Climate Change AI](https://www.climatechange.ai/)


## Example models

[RICE/DICE](https://williamnordhaus.com/dicerice-models), Regional Integrated model of Climate and the Economy (RICE) / Dynamic Integrated Climate Change (DICE)  [DICE 2023](https://yale.app.box.com/s/whlqcr7gtzdm4nxnrfhvap2hlzebuvvm)

[SWITCH](https://www.switch-model.org), A loose acronym for Solar, Wind, Hydro and Conventional generators and Transmission. Planning low-cost, low-carbon power system investments

[ReEDS](https://www.nrel.gov/analysis/reeds/), The Regional Energy Deployment System (ReEDS) is a long-term capacity expansion model for the deployment of electric power generation technologies and transmission infrastructure throughout the contiguous United States.

[SAM](https://sam.nrel.gov) , The System Advisor Model (SAM) is a performance and financial model designed to facilitate decision making in renewable energy.

[GCAM](https://www.globalchange.umd.edu/gcam), Global Change Assessment Model (GCAM), an integrated assessment tool for exploring consequences and responses to global change.

[C-ROADS](https://www.climateinteractive.org/simulations), Climate Rapid Overview and Decision Support

[LEAP](https://leap.sei.org/), The Long-range Energy Alternatives Planning System

[MARKAL](https://iea-etsap.org/index.php/etsaptool/model-generators/markal), Markal is a numerical model used to carry out an economic analysis of different energy related systems at the country level to represent its evolution over a period.

[MESSAGE](https://webarchive.iiasa.ac.at), Model for Energy Supply Strategy Alternatives and their General Environmental Impact

[GAINS](https://gains.iiasa.ac.at/models), The Greenhouse Gas and Air Pollution Interactions andSynergies (GAINS)-Model provides a consistent framework for the analysis of co-benefits reduction strategies from air pollution and greenhouse gas sources.

[NEMS](https://www.eia.gov), The National Energy Modeling System (NEMS) is a computer-based, energy-economy modeling system of U.S. through 2030.

[MERGE](https://eea.epri.com/models.html#tab=1), Model for Evaluating the Regional and Global Effects of GHG Reduction Policies

[Balmorel](https://www.balmorel.com), Balmorel is a model for analyzing the electricity and combined heat and power sectors in an international perspective.

[GridLAB-D](https://www.gridlabd.org), GridLAB-D is an open-source simulation and analysis tool that models emerging smart grid energy technologies.

[EnergyPlus](https://apps1.eere.energy.gov), EnergyPlus is a whole building energy simulation program that engineers, architects, and researchers use to model energy and water use in buildings.

[OSeMOSYS](https://www.osemosys.org): The Open Source Energy Modeling System

[TEMOA](https://www.temoaproject.org): Tools for Energy Model Optimization and Assessment

[PyPSA](https://pypsa.org/): Python for Power System Analysis


<!--Include social share buttons-->

{{< include /files/includes/_socialshare.qmd >}}
