---
title: Fall 2024 Course Schedule
page-layout: full
repo-actions: false
---

<!--This is my personal clarity, please delete or replace with your own clarity-->
{{< include /files/includes/_msclarity.qmd >}}

| Week | Date  | Lecture                                                                           | Guest Speaker                                                                                            | Assignment                 |
| ---- | ----- | --------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------- | -------------------------- |
| 1    | 9/2   | Labor Day - No session                                                            |                                                                                                          |                            |
| 2    | 9/9   | [Introduction: Grand challenges](lectures/lecture1.qmd)                           |                                                                                                          | [HW1](assignments/hw1.qmd) |
| 3    | 9/16  | [Make sense of energy and climate numbers](lectures/lecture2.qmd)                 | [Ketch Morse](https://drganghe.github.io/climate-guest-speakers/speakers/richard-morse/)                 |                            |
| 4    | 9/23  | [Climate impact and responses](lectures/lecture3.qmd)                             | [Shirley Gallagher](https://drganghe.github.io/climate-guest-speakers/speakers/shirley-gallagher/)       |                            |
| 5    | 9/30  | [Energy systems overview](lectures/lecture4.qmd)                                  | [Kaifang Luo](https://drganghe.github.io/climate-guest-speakers/speakers/kaifang-luo/)                   |                            |
| 6    | 10/7  | [Energy project economics](lectures/lecture5.qmd)                                 | [Simi George](https://drganghe.github.io/climate-guest-speakers/speakers/simi-george/)                   | [HW2](assignments/hw2.qmd) |
| 7    | 10/15 | [Energy demand, energy and economy](lectures/lecture6.qmd)                        | [Maryam Mozafari](https://drganghe.github.io/climate-guest-speakers/speakers/maryam-mozafari/)           |                            |
| 8    | 10/21 | [Energy sources and conversion technologies](lectures/lecture7.qmd)               | [Fabio Passaro](https://drganghe.github.io/climate-guest-speakers/speakers/fabio-passaro/)               | [HW3](assignments/hw3.qmd) |
| 9    | 10/28 | [Energy efficiency, behavior, and sustainable consumption](lectures/lecture8.qmd) | [Liqun Peng](https://drganghe.github.io/climate-guest-speakers/speakers/liqun-peng/)                     |                            |
| 10   | 11/4  | [Energy access, justice, and transition](lectures/lecture9.qmd)                   | [Samuel Vaillancourt](https://drganghe.github.io/climate-guest-speakers/speakers/samuel-vaillancourt/)   | HW4                        |
| 11   | 11/11 | [Energy, environment, climate, and human health](lectures/lecture9.qmd)           | [Bharathi Esakkimuthu](https://drganghe.github.io/climate-guest-speakers/speakers/bharathi-esakkimuthu/) | Proposal                   |
| 12   | 11/18 | Climate policy instruments                                                        | [Mohsen Fatemin](https://drganghe.github.io/climate-guest-speakers/speakers/mohsen-fatemi/)              |                            |
| 13   | 11/25 | Big data and AI for climate change [Thanksgiving week]                            |                                                                                                          |                            |
| 14   | 12/2  | Uncertainties in policy analysis                                                  |                                                                                                          |                            |
| 15   | 12/9  | Presentations                                                                     |                                                                                                          | Policy memo                |
