---
title: Assignment 2 What if Americans turned to small cars and electric vehicles?
format: 
  html: 
    theme: cosmo
    css: /styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
  pdf: 
    documentclass: article
    #classoption: [landscape]
    lof: false
    lot: false
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded
    #fontfamily: xelatex
    colorlinks: true
#draft: true
---

In your first policy response, you were asked to discuss the impact and policy responses to America's big car problem. This assignment will give you a chance to practice with data and policy analysis. You will navigate through some common energy and carbon data, make some reasonable assumptions, and calculate some policy relevant metrics. It's a plus if you can visualize your analysis.


## Questions

Please make reasonable assumptions and calculate the following questions:

1. First, let's make some assumptions on the market penetration of small cars and electric vehicles. Assume that starting from 2020, small cars (subcompact, compact, and midsize cars) make up 20% of all light-duty vehicles (cars and trucks) in the US, and electric vehicles make up 20% of all light-duty vehicles in the US. Calculate the total carbon emission reduction from this change.



## Further readings






