---
title: Assignment 2 Updating a Rosenfeld Plant
format: 
  html: 
    theme: cosmo
    css: /styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
  pdf: 
    documentclass: article
    #classoption: [landscape]
    lof: false
    lot: false
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded
    #fontfamily: xelatex
    colorlinks: true
#draft: true
---

We discussed [Defining a Rosenfeld Plant](https://drganghe.github.io/energy-climate-policy/lectures/lecture2.html#/defining-a-rosenfeld-plant) in Lecture 2. That paper was published in 2010, now more than a decade has past and let's update the Rosenfeld Plant to 2021.

To define a Rosenfeld Plant, you would need to figure out the average size of U.S. coal plants, the average capacity factor of those operating plants, average emission factor of coal power plants, and the average transmissin losses. You may able to find those statistics on the web, however, I hope you can use plant level data to calculate those by yourself.

## Data

There are a few places that you may find plant level data. 

- [EIA-860](https://www.eia.gov/electricity/data/eia860/) collects generator-level specific information about existing and planned generators and associated environmental equipment at electric power plants with 1 MW or greater of combined nameplate capacity.
- EPA [eGRID](https://www.epa.gov/egrid) includes emissions, emission rates, generation, heat input, resource mix, and many other attributes.
- Global Energy Monitor's [Global Coal Plant Tracker (GCPT)](https://globalenergymonitor.org/projects/global-coal-plant-tracker/) provides information on coal-fired power units from around the world generating 30 megawatts and above.

EIA's data is comprehensieve but a bit messy, GCPT data focuses on coal plants might not have the attributes you need. Let's use the EPA eGRID data for your analysis. Please [download](https://www.epa.gov/egrid/download-data) eGRID with 2021 data.


## Questions

Please use the eGRID data and work out the calculation:

- What's the average coal power plant size in the U.S. in 2021? (0.5pt)[Hint: the "PLT21" shows plant level data, and you can filter data by plant primary fuel to get all COAL plants]   
- What's the average capacity factor of coal plants in 2021? (0.5 pt) [Hint: use total generation and total capacity to calculate the average capacity factor]   
- What's the average carbon emission factor of coal plants in 2021? (0.5pt) [Hint: use total carbon emission and total generation to calculate the average emission factor]  
- Using the updated parameter, what's the total carbon emissions of an updated Rosenfeld Plant? (0.5pt)   
- What's the average efficiency of coal plants in 2021? (1pt) [Hint: use total plant annual net generation and total plant annual heat input to calculate the average efficiency]  
- If we can improve the average efficiency of coal plants by 1% (percent point), e.g. 32% to 33%, how many new Rosenfeld Plant we can avoid building? [Hint: use the same total coal generation] (1.5pt)   
- Further explore the data, what are the top 10 carbon emitting plants in the U.S. and think about how to reduce carbon emissions for those plants (1.5 pt)   

Note: please show your process to receive partial credit.   

Plug: eGRID has rich resources and we will come back to this assignment when discuss environmental and climate justice.

## Further readings

- Koomey, Jonathan, Hashem Akbari, Carl Blumstein, Marilyn Brown, Richard Brown, Chris Calwell, Sheryl Carter, et al. 2010. “Defining a Standard Metric for Electricity Savings.” *Environmental Research Letters* 5 (1): 014017. <https://doi.org/10.1088/1748-9326/5/1/014017>.




