## Academic Support  

Visiting Baruch’s academic support services is correlated with higher grades. I encourage all students in this course to take advantage of these services: visit the tutors at SACC, work with the consultants at the Writing Center and Tools for Clear Speech, and take advantage of office hours! Visit early and often!

Early in the semester, I’ll receive a survey that asks me to identify students who might be struggling in class. Those I name will be prompted by an email or text to visit one of our support services. Please respond to those invitations to meet with a tutor or consultant! Students who visit these services do better in their classes than students who don’t. 

There’s no need to wait for an alert message to get help—you can start working with tutors from the start of the semester. Want more information? Try these links: 

### SACC (Student Academic Consulting Center) 

SACC supports the academic success of undergraduates at Baruch College through small group peer tutoring and other programs, serving students in a wide variety of subjects across the curriculum. 

<https://sacc.baruch.cuny.edu/> 

### Writing Center 
The Writing Center offers free support to all Baruch students. Our professional consultants work collaboratively with you to deepen your writing and English language skills. 

<https://blogs.baruch.cuny.edu/writingcenter/>

### Tools for Clear Speech  

TfCS offers a broad range of free tutorial sessions, workshops, and online practice to enhance the oral communication skills of Baruch’s non-native English-speakers, multilinguals, and English language learners. 

<https://tfcs.baruch.cuny.edu/> 
